<a href="https://codeimmersives.com"><img src = "https://www.codeimmersives.com/wp-content/uploads/2019/09/CodeImmersives_Logo_RGB_NYC_BW.png" width = 400> </a>


<h1 align=center><font size = 5>Agenda</font></h1>

### 
<div class="alert alert-block alert-info" style="margin-top: 20px">

1.  [Review](#0)<br>
2.  [Numpy Intro and Installation](#2)<br>
2.  [Exercise](#10)<br> 
3.  [Exercise](#12)<br>     
</div>
<hr>

<h2>Review</h2>

<h2>Exercise</h2>
The following list represents the diameters of circles:<br>
<code>
circle_diameters = [1,2,3,5,8,13,21]
</code><br>
1 - Calculate the area of each circle<br>
2 - Calculate the circumference of each circle<br>
<br>
Use Numpy for the solution

<h4>Solution</h4>

In [ ]:
import numpy as np
circle_diameters = [1,2,3,5,8,13,21]
area = [round(np.pi*(x/2)**2,2) for x in circle_diameters]
circ = [round(np.pi*x) for x in circle_diameters]
print(circ)
print(area)

<h2>Exercise</h2>
For each tuple in the list print the area of each rectangle<br><br>
Each element in the list represents the length and the width
<code>
dimensions = [(20,2),(2,3),(4,4),(6,6)]
</code><br>
Solve as a non numpy problem

<h4>Solution</h4>

In [ ]:
dimensions = [(20,2),(2,3),(4,4),(6,6)]
areas = [i*x for i,x in dimensions]
print(areas)

[40, 6, 16, 36]


<h2>Exercise</h2>
The following dictionary represents the dimensions of an apartment in <br>
New York City.  <br><br>
<code>
apartment = {'Bedroom 1':(12,12), 'Bedroom 2': (12,10), 'Bathroom 1': (6,8),
    'Bathroom 2': (6,8), 'Kitchen': (10,8), 'Foyer': (14,4), 'Dining Room': (12,10),
    'Living Room': (12,15)}
</code><br>
1 - Calculate the square footage of each room<br>
2 - Calculate the total square footage of the apartment<br>
3 - If the apartment is selling for $90 a square foot.  How much is it selling for?<br><br>
NOTE: Selling price is the Square footage * price per square foot as 12<br>
Do not use numpy

In [ ]:
apartment = {'Bedroom 1':(12,12), 'Bedroom 2': (12,10), 'Bathroom 1': (6,8), 'Bathroom 2': (6,8), 'Kitchen': (10,8), 'Foyer': (14,4), 'Dining Room': (12,10), 'Living Room': (12,15)}
areas = [(v[0]*v[1]) for i,v in apartment.items()]
print(areas)
print(sum(areas))
print('$',sum(areas)*90)

[144, 120, 48, 48, 80, 56, 120, 180]
796
$ 71640


<h2>Exercise</h2>
5 friends go out to dinner and their individual amounts were tallied on 1 bill<br>
<code>
dinner = [36, 42, 27, 32, 39]
</code><br>
Using numpy calculate the following:<br>
1 - The average meal price<br>
2 - The median meal price<br>
3 - The maximum cost for the meal<br>
4 - The least expensive meal<br>
5 - The difference each person varied from the mean<br>
6 - Add a 20% tip to each persons meal then Add 8.875% tax to the pre tax meal amount<br>
7 - What percentage of the total bill is each person contributing?<br>
8 - It was the birthday of the person who had the most expensive meal.  <br>
Distribute the cost of their meal amoungst the other patrons.<br>

<h4>Solution</h4>

In [ ]:
import numpy as np
dinner = [36, 42, 27, 32, 39]
avg = np.mean(dinner)
median = np.median(dinner)
m = np.max(dinner)
mi = np.min(dinner)
diff_mean = [round(x-avg,2) for x in dinner]
print('avg:', avg, 'median:', median, 'max:', m, 'min:', mi)
print(diff_mean)

adjusted_dinner = [round((x*1.2)*1.0875,2) for x in dinner]
new_sum = sum(adjusted_dinner)
print(adjusted_dinner)

contributions = [round((x/new_sum)*100,2) for x in adjusted_dinner]
print(contributions, sum(contributions))

add = np.max(adjusted_dinner)/4 
adjusted_dinner.remove(max(adjusted_dinner))
print(np.add(adjusted_dinner,add))


avg: 35.2 median: 36.0 max: 42 min: 27
[0.8, 6.8, -8.2, -3.2, 3.8]
[46.98, 54.81, 35.23, 41.76, 50.89]
[20.46, 23.86, 15.34, 18.18, 22.16] 100.0
[60.6825 48.9325 55.4625 64.5925]


<h2>Numpy continued</h2>

Strings can also be stored in a numpy array.<br>
<code>
import numpy as np
pasta_shapes = ['Macaroni','Rigatoni','Angel Hair','Spaghetti','Linguini']
shapes = np.array(pasta_shapes)
shapes = np.sort(shapes)
print(shapes)
print(shapes.dtype)
</code>

In [ ]:
import numpy as np 
pasta_shapes = ['Macaroni','Rigatoni','Angel Hair','Spaghetti','Linguini']
val= 5
val = np.array(val)
name= 'str'
name = np.array(name)
boo = True
boo = np.array(boo)

shapes = np.array(pasta_shapes)
print(np.sort(shapes))
print(type(shapes))

['Angel Hair' 'Linguini' 'Macaroni' 'Rigatoni' 'Spaghetti']
<U10
<class 'numpy.ndarray'>


We can use short cut abreviations to assign the data types to numpy<br>
arrays:<br>
For i, u, f, S and U we can define size as well. <br>
We can combine each letter with a size as well like: 4,8<br>
<br>
<code>
import numpy as np
arr = np.array(list(range(1,11)), dtype='i8')
print(arr, arr.dtype)
</code>

In [ ]:
import numpy as np
np.array(list(range(1,11)), dtype='i8') 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

<h2>Casting</h2>
We can convert python data type into numpy data type using 2 methods<br>
<br>
Method 1<br>
Use dtype parameter<br>
<br>
<code>
arr_string = np.array(list(range(1,11)), dtype='S')
print(arr_string)
</code><br>
Method 2<br>
Use astype()<br>
<code>
import numpy as np
arr = np.array(list(range(1,11)), dtype='i8')
arr_2 = arr.astype('S')
print(arr_2)
</code>

In [ ]:
arr_string = np.array(list(range(1,11))) 
print(arr_string)
import numpy as np
arr = np.array(list(range(1,11)), dtype='i8')
arr_2 = arr.astype('S')
print(arr_2)


[ 1  2  3  4  5  6  7  8  9 10]
[b'1' b'2' b'3' b'4' b'5' b'6' b'7' b'8' b'9' b'10']


<h2>Exercise</h2>
Take the following floating point number and cast them as integers<br>
Use both methods.<br>
<code>
rainfall = [2.3,3.7,2.4,1.9]
</code>

<h4>Solution</h4>

In [ ]:
import numpy as np
rainfall = np.array([2.3,3.7,2.4,1.9])
r2 = rainfall.astype(int)
print(r2)
 


[2 3 2 1]


In [ ]:
import numpy as np
 


This notebook is part of a course at www.codeimmersives.com called Data Science. If you accessed this notebook outside the course, you can get more information about this course online by clicking here.

<hr>

Copyright &copy; 2021  Code Immersives