<a href="https://codeimmersives.com"><img src = "https://www.codeimmersives.com/wp-content/uploads/2019/09/CodeImmersives_Logo_RGB_NYC_BW.png" width = 400> </a>


<h1 align=center><font size = 5>Agenda</font></h1>

### 
<div class="alert alert-block alert-info" style="margin-top: 20px">

1.  [Review](#0)<br>
2.  [Numpy continued](#2)<br>
2.  [Exercise](#10)<br> 
3.  [Exercise](#12)<br>     
</div>
<hr>

<h2>Review</h2>

Each array has attributes ``ndim`` (the number of dimensions), ``shape`` (the size of each dimension), and ``size`` (the total size of the array):

In [ ]:
import numpy as np
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


<h4> Array Arithmetic </h4>
Vectorized operations in NumPy are implemented via *ufuncs*, whose main purpose is to quickly execute repeated operations on values in NumPy arrays. We also call this element-wise arithmetic.




In [ ]:
x = np.array([1,2,3,4])
y = np.array([2,3,4,5])
print(x+y)

[3 5 7 9]


In [ ]:
np.arange(5)/np.arange(1,6)
print(np.arange(5)/np.arange(1,6))
print(np.arange(5))
print(np.arange(1,6))


[0.         0.5        0.66666667 0.75       0.8       ]
[0 1 2 3 4]
[1 2 3 4 5]


In [ ]:
np.add(x, 2)

All the arithmetic operators implemented in NumPy:

| Operator	    | Equivalent ufunc    | Description                           |
|---------------|---------------------|---------------------------------------|
|``+``          |``np.add``           |Addition (e.g., ``1 + 1 = 2``)         |
|``-``          |``np.subtract``      |Subtraction (e.g., ``3 - 2 = 1``)      |
|``-``          |``np.negative``      |Unary negation (e.g., ``-2``)          |
|``*``          |``np.multiply``      |Multiplication (e.g., ``2 * 3 = 6``)   |
|``/``          |``np.divide``        |Division (e.g., ``3 / 2 = 1.5``)       |
|``//``         |``np.floor_divide``  |Floor division (e.g., ``3 // 2 = 1``)  |
|``**``         |``np.power``         |Exponentiation (e.g., ``2 ** 3 = 8``)  |
|``%``          |``np.mod``           |Modulus/remainder (e.g., ``9 % 4 = 1``)|


<h4> Array Indexing: Accessing Single Elements </h4>
Done the exact same way as with Python lists. In multi-dimensional numpy arrays, we can index multiple times to access values. 


In [ ]:
x1 = np.random.randint(10, size=6)  # One-dimensional array
x1[0]
x1[-1]
print(x1)
x1[2:6:2]



[2 6 5 9 7 4]


array([5, 7])

In [ ]:
import numpy as np
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
print(x2)
#x2[0, 0]
#x2[1, 0]
x2[::-1,::-1]
#np.flip(x2,axis=1)
#x2[1, -1]

[[3 0 3 1]
 [2 6 4 6]
 [9 4 1 3]]


array([[3, 1, 4, 9],
       [6, 4, 6, 2],
       [1, 3, 0, 3]])

## Slicing Arrays

To access subsections of a larger array, we use the : operation to *slice* a specified part of the array.

``` python
x[start:stop:step]
```
If any of these are unspecified, they default to the values ``start=0``, ``stop=``*``size of dimension``*, ``step=1``.
We'll take a look at accessing sub-arrays in one dimension and in multiple dimensions.

In [ ]:
x = np.arange(10)
x[:3]  # first three elements
x[5:] #elements after index 5 
x[4:7]  # middle sub-array
x[::-1]  # all elements, reversed

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

<h4>Reshaping Arrays</h4>
Simply call array.reshape(new_shape) on your old array with a new shape. Make sure the shape size is compatible with the array length (factors).

In [ ]:
grid = np.arange(1, 11).reshape((5, 2))
print(grid)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


<h2>Exercise</h2>
Create a numpy array with 2 dimensions, a shape of 5x5, and calculate the array's size.

<h4>Solution</h4>

<h2>Exercise</h2>


Create a 1-D array of 8 values using np.arange(8), and then reshape it to a 3-dimensional array using the array.reshape(new_shape) function. 
*HINT* look at the cubic of 8 to find the appropriate shape.

<h4>Solution</h4>

In [ ]:
n1 = np.arange(8)
print(n1)
n2 = n1.reshape((2,2,2))
print(n2)

[0 1 2 3 4 5 6 7]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


<h2>Exercise</h2>


<h2>Numpy continued</h2>
We will explore Numpy ufuncs, which stand for 'Universal Functions', that<br>
operate on the ndarray object.<br>
ufuncs are used to implement vectorization in NumPy which is way faster than <br>
iterating over elements.<br>
<br>
They also provide broadcasting and additional methods like reduce, accumulate etc. <br>
that are very helpful for computation.<br>
<br>
ufuncs also take additional arguments, <br>
like:<br>

- where - boolean array or condition defining where the operations should take place.<br>
- dtype - defining the return type of elements.<br>
- out - output array where the return value should be copied.<br>

<h4>Adding 2 python lists together</h4>
<br>
<code>
x = [3, 5, 7, 9]
y = [4, 6, 8, 10]
z = np.add(x, y)

print(z)  
print(type(z))
</code>
<br>
NOTE: The shape of the numpy objects must be the same.

In [ ]:
x = np.array([3, 5, 7, 9])
y = np.array([4, 6, 8, 10])
z = x+y
print(z)


[ 7 11 15 19]


<h4>Subtraction</h4>
<br>
<code>
x = [13, 25, -7, 39]
y = [4, 6, 8, 10]
z = np.subtract(x, y)

print(z)
print(type(z))
</code>

In [ ]:
z = np.subtract(x, y)

<h4>Multiplication</h4>
<code>
x = [13, 25, -7, 39]
y = [4, 6, 8, 10]
z = np.multiply(x, y)

print(z)
print(type(z))
</code>

In [ ]:
x = [13, 25, -7, 39]
y = [4, 6, 8, 10]
z = np.multiply(x, y)
print(z)

[ 52 150 -56 390]


<h4>Division</h4>
<code>
import numpy as np

arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 5, 8, 13, 21, 34])

newarr = np.divide(arr1, arr2)
print(newarr) 
</code>
<br>
Powers
<code>
arr1 = np.array([2, 3, 4, 5, 6, 7])
arr2 = np.array([7, 6, 5, 4, 3, 2])

newarr = np.power(arr1, arr2)
print(newarr) 
</code>
<br>
Reminder/ Modulus
<code>
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 7, 6, 14, 8, 13])
newarr = np.remainder(arr1, arr2)

print(newarr) 


arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 7, 9, 8, 2, 33])

newarr = np.mod(arr1, arr2)

print(newarr) 
</code>
<br>
Quotient and Mod
<code>
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([2, 5, 9, 8, 13, 43])
newarr = np.divmod(arr1, arr2)   # Returns 2 arrays !!!

print(newarr) 
</code>
<br>
Absolute Value
<code>
arr = np.array([-1, -2, 10, 2, 13, -9])
newarr = np.absolute(arr)

print(newarr) 
</code>

In [ ]:
arr1 = np.array([2, 3, 4, 5, 6, 7]) 
arr2 = np.array([7, 6, 5, 4, 3, 2])
print(np.power(arr1,arr2))

[ 128  729 1024  625  216   49]


<h2> Try them Out! </h2>

<h2>Exercise</h2>


a1 = np.array([[1,2],
               [3,4],
               [5,6]])

a2 = np.array([[7,8],
               [9,10],
               [10,11]])

Reshape the two arrays into 1-D arrays and add them, print the sum.


In [ ]:
a1 = np.array([[1,2], [3,4], [5,6]])
a2 = np.array([[7,8], [9,10], [10,11]])
a1 = a1.reshape(6,)
a2 = a2.reshape(6,)
print(np.add(a1,a2))

[ 8 10 12 14 15 17]


<h2>Numpy ufunc - Rounding Decimals</h2><br>
There are primarily five ways of rounding off decimals in NumPy:<br>
- truncation - remove the decimal portion of a number
<br>
<code>
import numpy as np
arr = np.trunc([-3.1666, 3.6667, 111.23334])
print(arr)    
</code><br>
- rounding - equivalent to python rounding
<br>
<code>
arr = np.around(3.1417, 2)
print(arr)     
</code><br>
- floor - Returns the next lower integer number
<br>
<code>
arr = np.floor([-3.1666, 3.6667])
print(arr)     
</code><br>
- ceil - Returns the next higher integer number
<br>
<code>
arr = np.ceil([-3.1666, 3.6667])
print(arr)     
</code><br>

Exercise: round pi to the nearest 5 digits using numpy and use to calculate the area of a circle with radius 3. 

In [ ]:
print(np.pi)

3.141592653589793


<h2>Summing all elements</h2>
We can use the Numpy sum function to add up all of the values in<br>
1 or more np.arrays<br>
<code>
import numpy as np

arr1 = np.array([3, 4, 1])
arr2 = np.array([-1,-2, 7])
newarr = np.sum([arr1, arr2])
print(newarr) 
</code>

In [ ]:
import numpy as np

arr1 = np.array([3, 4, 1])
arr2 = np.array([-1,-2, 7])

newarr = np.sum([arr1, arr2])
print(newarr) 

In [ ]:
big_array = np.random.rand(1000000)

%timeit min(big_array)
%timeit np.min(big_array)
#np.max

10 loops, best of 5: 104 ms per loop
The slowest run took 5.56 times longer than the fastest. This could mean that an intermediate result is being cached.
1000 loops, best of 5: 413 µs per loop


Exercise:
There are 10 customers with account holdings given below. We want to separate customers with an total holding of more than 1,000 dollars (commercial accounts) and those with less than 1,000 dollars (personal accounts). 
<br>
1) what is the total commercial account value?
<br>
2) using np.max() what is the highest account holding amongst the personal accounts? <br>

We want to aggregate all the personal and commercial account holdings into separate arrays. 
<br>
3) Find the mean and stdev of the personal account list. 
<br>
4) Find the median and mean of the commercial account list.   
<br>
We'd like to plot the commercial account holdings against the personal account holdings. <br>
5) Import matplotlib and use the plt.scatter(x,y) method to print a graph depicting this relationship. <br>


<code>
c1 = np.array([155, 204, 312, 56])
c2 = np.array([233, 245, 333])
c3 = np.array([802, 7, 382, 9329, 58392])
c4 = np.array([222, 453, 10235, 9929])
c5 = np.array([902, 75, 29394])
c6 = np.array([65, 45])
c7 = np.array([550, 300])
c8 = np.array([200, 120])
c9 = np.array([550, 1200])
c10 = np.array([5312, 0])
</code>

In [ ]:
import numpy as np
c1 = np.array([155, 204, 312, 56]) 
c2 = np.array([233, 245, 333]) 
c3 = np.array([802, 7, 382, 9329, 58392]) 
c4 = np.array([222, 453, 10235, 9929]) 
c5 = np.array([902, 75, 29394]) 
c6 = np.array([65, 45]) 
c7 = np.array([550, 300]) 
c8 = np.array([200, 120]) 
c9 = np.array([550, 1200]) 
c10 = np.array([5312, 0])
c11 = np.array([150, 200, 20])
clist = [c1,c2,c3,c4,c5,c6,c7,c8,c9,c10,c11]
comm = np.array(0)
pers = np.array(0)
for i in clist:
  if i.sum() > 1000:
    comm = np.append(comm, i) 
    #np.add; np.insert, np.concatenate
  else:
    pers = np.append(pers,i)
comm = np.delete(comm, 0)
pers = np.delete(pers, 0)
print('commercial value sum: $', np.sum(comm))
print('highest personal holding: $', np.max(pers))
print(np.mean(pers))
print(np.std(pers))
print(np.median(comm))
print(np.mean(comm))
print(len(comm), len(pers))
print(pers)
plt.scatter(pers, comm)
plt.show()


This notebook is part of a course at www.codeimmersives.com called Data Science. If you accessed this notebook outside the course, you can get more information about this course online by clicking here.

## Intro Dataloading Example: What is the Average Height of US Presidents?

Aggregates available in NumPy can be extremely useful for summarizing a set of values.
As a simple example, let's consider the heights of all US presidents.
This data is available in the file *president_heights.csv*, which is a simple comma-separated list of labels and values:

In [ ]:
!head -4 data/president_heights.csv

head: cannot open 'data/president_heights.csv' for reading: No such file or directory


We'll use the Pandas package, which we'll explore more fully next class to read the file and extract this information (note that the heights are measured in centimeters).

In [ ]:
import pandas as pd
import numpy as np
data = pd.read_csv('president_heights.csv')
heights = np.array(data['height(cm)'])
print(heights)

[189 170 189 163 183 171 185 168 173 183 173 173 175 178 183 193 178 173
 174 183 183 168 170 178 182 180 183 178 182 188 175 179 183 193 182 183
 177 185 188 188 182 185]


Now that we have this data array, compute summary statistics (mean, stdev, min, and max of height):

In [ ]:
print("Mean height:       ", heights.mean())
print("Standard deviation:", heights.std())
print("Minimum height:    ", heights.min())
print("Maximum height:    ", heights.max())

Mean height:        179.73809523809524
Standard deviation: 6.931843442745892
Minimum height:     163
Maximum height:     193


Now calcualte the quartiles using np.percentile(data, percentile) for the 1st quartile (25%), 2nd quartile (50%), and third quartile (75%). 

In [ ]:
print("25th percentile:   ", np.percentile(heights, 25))
print("Median:            ", np.median(heights))
print("75th percentile:   ", np.percentile(heights, 75))

25th percentile:    174.25
Median:             182.0
75th percentile:    183.0


Once you get the average height, try plotting this in a histogram chart (hint: use plt.hist())

In [ ]:
import matplotlib.pyplot as plt
plt.hist(heights)
plt.title('Height Distribution of US Presidents')
plt.xlabel('height (cm)')
plt.ylabel('number');

<hr>

Copyright &copy; 2021  Code Immersives